# Generated by Django 5.2 on 2025-04-25 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the custom order in detail')),
                ('size', models.CharField(help_text='Size of the artwork (e.g., A4, A3, etc.)', max_length=50)),
                ('colours', models.CharField(help_text='Preferred colours for the artwork', max_length=255)),
                ('theme', models.CharField(help_text='Theme of the artwork (e.g., nature, abstract, etc.)', max_length=255)),
                ('style', models.CharField(help_text='Preferred style of the artwork (e.g., realism, impressionism, etc.)', max_length=255)),
                ('extra_suggestions', models.TextField(blank=True, help_text='Any extra suggestions, requirments or notes for the artist')),
                ('contact_email', models.EmailField(help_text='Email address for the artist to contact the user', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
