# Generated by Django 5.2 on 2025-04-25 09:12

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your Artist name.', max_length=255)),
                ('interests', models.TextField(blank=True, help_text='List your artistic interests.')),
                ('background', models.TextField(help_text='Tell your story as an artist.')),
                ('inspiration', models.TextField(help_text='What inspires your work?')),
                ('work_experience', models.TextField(blank=True, help_text='Share your past projects or exhibitions.')),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_bio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
