# Generated by Django 5.2 on 2025-04-23 19:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_artwork_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
