# Generated by Django 5.2 on 2025-04-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_alter_artwork_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='style',
            field=models.CharField(choices=[('modern', 'Modern'), ('traditional', 'Traditional'), ('contemporary', 'Contemporary'), ('impressionism', 'Impressionism')], default='impressionism', max_length=100),
        ),
        migrations.AddField(
            model_name='artwork',
            name='theme',
            field=models.CharField(choices=[('abstract', 'Abstract'), ('landscape', 'Landscape'), ('fantasy', 'Fantasy'), ('travel', 'Travel'), ('nature', 'Nature')], default='landscape', max_length=100),
        ),
    ]
